kcctl/kcctl

.github/workflows/early-access.yml, .github/workflows/maven.yml, .gitignore, jreleaser.yml, pom.xml, src/main/assembly/assembly-windows.xml, src/main/assembly/assembly.xml
Fixes https://github.com/gunnarmorling/kcctl/issues/10
- Add Maven configuration for creating Native Image distributions -> https://jreleaser.org/guide/latest/distributions/native-image.html
- Build main branch on every push.
- Publish rolling releases only when pushing to `main`.
=> Publish binary releases

.github/workflows/early-access.yml, .github/workflows/maven.yml, .github/workflows/release.yml
This PR configures a release workflow for stable versions.
A release must be triggered manually from the workflows tab. There are 2 inputs:
* the version to be released, i.e, `1.0.0.Alpha1`. (REQUIRED)
* the next development version, i.e, `1.1.0-SNAPSHOT`. (OPTIONAL)
The next development version will be automatically calculated from the current version, that is, use the `d.d.d` value and append `-SNAPSHOT`. No number will be automatically incremented as the `maven-release-plugin` does because one could go from `1.0.0.Final` into `1.1.0-SNAPSHOT` (or even `2.0.0-SNAPSHOT` !!) where as the maven release plugin will always increment the build number, resulting in `1.0.1-SNAPSHOT` for example instead of `1.1.0-SNAPSHOT`. Also, the release plugin would require using the …
=> 🌟 Configure release workflow

README.md, src/main/java/dev/morling/kccli/command/KcCtlCommand.java, src/main/java/dev/morling/kccli/command/PauseCommand.java, src/main/java/dev/morling/kccli/command/PauseConnectorCommand.java, src/main/java/dev/morling/kccli/command/ResumeCommand.java, src/main/java/dev/morling/kccli/command/ResumeConnectorCommand.java, src/main/java/dev/morling/kccli/service/KafkaConnectApi.java
Add two new commands to support pause and resume kafka connectors #1 
1- `kcctl pause connector connector-name-1`
2- `kcctl resume connector connector-name-1`
=> Add pause and resume connector commands

README.md, kcctl_completion, pom.xml, src/main/java/dev/morling/kccli/command/ApplyCommand.java, src/main/java/dev/morling/kccli/command/ConnectorNamesCompletionCandidateCommand.java, src/main/java/dev/morling/kccli/command/DeleteConnectorCommand.java, src/main/java/dev/morling/kccli/command/DescribeConnectorCommand.java, src/main/java/dev/morling/kccli/command/GetConnectorsCommand.java, src/main/java/dev/morling/kccli/command/GetContextCommand.java, src/main/java/dev/morling/kccli/command/GetLoggerCommand.java, src/main/java/dev/morling/kccli/command/GetLoggersCommand.java, src/main/java/dev/morling/kccli/command/GetPluginsCommand.java, src/main/java/dev/morling/kccli/command/InfoCommand.java, src/main/java/dev/morling/kccli/command/LoggerNamesCompletionCandidateCommand.java, src/main/java/dev/morling/kccli/command/PatchConnectorCommand.java, src/main/java/dev/morling/kccli/command/PatchLogLevelCommand.java, src/main/java/dev/morling/kccli/command/PauseConnectorCommand.java, src/main/java/dev/morling/kccli/command/RestartConnectorCommand.java, src/main/java/dev/morling/kccli/command/RestartTaskCommand.java, src/main/java/dev/morling/kccli/command/ResumeConnectorCommand.java, src/main/java/dev/morling/kccli/command/SetContextCommand.java, src/main/java/dev/morling/kccli/command/TaskNamesCompletionCandidateCommand.java, src/main/java/dev/morling/kccli/service/Configuration.java, src/main/java/dev/morling/kccli/service/Context.java, src/main/java/dev/morling/kccli/util/ConfigurationContext.java, src/test/java/dev/morling/kccli/util/ConfigurationContextTest.java
Hi @gunnarmorling,
here comes the PR! I hope I've got the the requirements right 😄.
One thing I would like to challenge is supporting the old, properties-like config format. Because we are still pre 1.0.0, I guess it would be acceptable to not support the current (properties-like) configuration format anymore. Wdyt?
The current, context-aware format is very flexible, except for the context-name and cluster URL, every other property is
optional.
So both
```json
{
"currentContext": "local",
"local": {
"cluster": "http://localhost:8083"
}
}
```
and
```json
{
"currentContext": "local",
"local": {
"cluster": "http://localhost:8083",
"boostrapServers": "localhost:9092",
"offsetTopic": "connect-offsets"
}
}
```
are valid.
Fixes #24.
=> Add support for multiple configuration contexts

kcctl_completion, src/main/java/dev/morling/kccli/command/ApplyCommand.java, src/main/java/dev/morling/kccli/service/ConfigInfos.java, src/main/java/dev/morling/kccli/service/KafkaConnectApi.java
I've been playing quite a bit with the `/config/validate` endpoint in the past couple of days, so I thought I'd try adding support for it!
I've added it to `apply`, so currently the syntax to validate a configuration is:
```
kcctl apply -f /tmp/config.json --validate
```
Not fully sold on the flag name, maybe `--validate-only` is more explicit.
It's working with the same file as when creating a connector. Internally, it's hiding that `/config/validate` only wants the inner `config` part. I think it makes sense to validate and create connectors with the same exact file. I'm not a big fan of the Connect REST API expecting different payloads for both operations.
I've not properly tested all possible error paths yet but I wanted to see if the overall shape is what you had in mind.
=> Initial config validation logic

src/main/resources/application.properties
When calling the Kafka Connect API behind a proxy i get this error :
```
kkcctl info
javax.ws.rs.RedirectionException: HTTP 302 Found
at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.extractResult(ClientInvocation.java:237)
at org.jboss.resteasy.client.jaxrs.internal.proxy.extractors.BodyEntityExtractor.extractEntity(BodyEntityExtractor.java:64)
at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:154)
at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:115)
at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
at jdk.proxy4.$Proxy220.getWorkerInfo(Unknown Source)
at java.lang.reflect.Method.invoke(Method.java:568)
at …
```
=> feat: follow redirects when calling Kafka Connect API

pom.xml, src/test/java/org/kcctl/IntegrationTest.java, src/test/java/org/kcctl/command/ApplyCommandTest.java, src/test/java/org/kcctl/command/DescribeConnectorCommandTest.java, src/test/java/org/kcctl/command/GetPluginsCommandTest.java, src/test/java/org/kcctl/command/InfoCommandTest.java, src/test/java/org/kcctl/command/PatchCommandTest.java, src/test/resources/heartbeat-source-2.json, src/test/resources/heartbeat-source-bad.json, src/test/resources/heartbeat-source-update.json, src/test/resources/heartbeat-source.json, src/test/resources/local-file-source-2.json, src/test/resources/local-file-source-bad.json, src/test/resources/local-file-source-update.json, src/test/resources/local-file-source.json
Debezium 1.9.5 switched to Kafka Connect 3.2.0. In that version, the `FileStream` connectors have been removed from the classpath, because of [KAFKA-13748](https://issues.apache.org/jira/browse/KAFKA-13748).
Kcctl integration tests automatically pick the latest Debezium so some of the tests that rely on `FileStreamSource` are not working anymore.
To address this issue, I decided to update the integration tests to instead use `MirrorHeartbeatConnector`.
Another alternative would be to update `debezium/connect` to optionally re-enable the `FileStream` connectors. Since this is only fixing tests and this has some security implications I decided to not follow this approach. If you think this would be preferable I can make the changes.
=> ⤴️ Fixes for Connect 3.2

src/main/java/org/kcctl/command/DeleteCommand.java, src/main/java/org/kcctl/command/DeleteConnectorCommand.java, src/main/java/org/kcctl/command/KcCtlCommand.java, src/test/java/org/kcctl/IntegrationTest.java, src/test/java/org/kcctl/command/DeleteCommandTest.java, src/test/java/org/kcctl/support/KcctlCommandContext.java
Addresses #265
The `delete` command is replaced with `delete connector`. A useful error message is added to let users know about the replacement.
=> #265 replace 'delete' with 'delete connector'

src/main/java/org/kcctl/command/ApplyCommand.java, src/test/java/org/kcctl/command/ApplyCommandTest.java
Addresses #250 
Allows multiple files to be specified following a single `-f` flag, in order to work better with shell globbing.
I looked into the possibility of disallowing multiple `-f` flags from being specified, but based on https://github.com/remkop/picocli/issues/190 (which doesn't touch on that exact feature, but something related) and the picocli Javadocs, it appears that that's not supported.
=> #250 Allow multiple file names with 'apply -f'

pom.xml
See #285 for more context. Splits changes into dependabot related dependencies and other changes.
=> chore: Split changelog entries by dependencies and other changes

src/main/java/org/kcctl/command/ApplyCommand.java, src/test/java/org/kcctl/command/ApplyCommandTest.java, src/test/resources/nonexistent.json
=> #295 Fix NPE for listing plugins when connector class not found

src/main/java/org/kcctl/command/ApplyCommand.java, src/test/java/org/kcctl/command/ApplyCommandTest.java
Follow-up that fixes a small bug in https://github.com/kcctl/kcctl/pull/299 and adds better testing coverage for the list-connectors-when-class-not-found logic in `apply`.
=> #295 (follow-up) Fix configuration context for listing plugins when apply fails

.github/workflows/early-access.yml, .github/workflows/maven.yml, .github/workflows/release.yml, pom.xml
Brings the following changes:
- CI: use `-ntp` Maven flag to avoid long logs
- CI: use job output vars instead of files to share data between jobs
- CI: use env vars as constants for common values
- JReleaser: move packagers inside distributions section
Fixes #311
=> Update release configuration

README.md, kcctl_completion, src/main/java/org/kcctl/command/KcCtlCommand.java, src/main/java/org/kcctl/command/StopCommand.java, src/main/java/org/kcctl/command/StopConnectorCommand.java, src/main/java/org/kcctl/service/KafkaConnectApi.java, src/main/java/org/kcctl/util/Colors.java, src/test/java/org/kcctl/IntegrationTest.java, src/test/java/org/kcctl/command/GetOffsetsCommandTest.java, src/test/java/org/kcctl/command/StopConnectorCommandTest.java, src/test/java/org/kcctl/support/KcctlCommandContext.java
Addresses https://github.com/kcctl/kcctl/issues/339
Usage:
```
Usage: kcctl stop connector [-e] [NAME...]
Stops (but does not delete) the specified connector(s)
[NAME...]   Name(s) of the connector(s) (e.g. 'my-connector').
-e, --reg-exp   use NAME(s) as regexp pattern(s) to use on all connectors
```
Uses the `PUT /connectors/{name}/stop` endpoint introduced in [KIP-875](https://cwiki.apache.org/confluence/display/KAFKA/KIP-875%3A+First-class+offsets+support+in+Kafka+Connect#KIP875:FirstclassoffsetssupportinKafkaConnect-Endpoints) to stop (but not delete) connectors.
Similar to the 'get offsets' command, this feature requires Kafka Connect 3.5 or later, and the integration test is customized to use a non-stable version of Debezium (2.4.0 alpha). We can and should update the version used …
=> #339 Add 'stop connector' command

src/test/java/org/kcctl/IntegrationTest.java, src/test/java/org/kcctl/command/ApplyCommandTest.java, src/test/java/org/kcctl/command/ConnectorNamesCompletionCandidateCommandTest.java, src/test/java/org/kcctl/command/DeleteConnectorCommandTest.java, src/test/java/org/kcctl/command/DescribeConnectorCommandTest.java, src/test/java/org/kcctl/command/DescribePluginCommandTest.java, src/test/java/org/kcctl/command/GetConnectorsCommandTest.java, src/test/java/org/kcctl/command/GetLoggerCommandTest.java, src/test/java/org/kcctl/command/GetLoggersCommandTest.java, src/test/java/org/kcctl/command/GetOffsetsCommandTest.java, src/test/java/org/kcctl/command/GetPluginsCommandTest.java, src/test/java/org/kcctl/command/InfoCommandTest.java, src/test/java/org/kcctl/command/LoggerNamesCompletionCandidateCommandTest.java, src/test/java/org/kcctl/command/PatchCommandTest.java, src/test/java/org/kcctl/command/PauseConnectorCommandTest.java, src/test/java/org/kcctl/command/RestartConnectorCommandTest.java, src/test/java/org/kcctl/command/ResumeConnectorCommandTest.java, src/test/java/org/kcctl/command/StopConnectorCommandTest.java, src/test/java/org/kcctl/support/KcctlCommandContext.java
- Replaces consecutive calls to `IntegrationTest::registerTestConnector` with single calls to `IntegrationTest::registerTestConnectors`
- Replaces all manual verifications that a command exited with status zero with `KcctlCommandContext::runAndCheckExitCode`, which on top of asserting that the command exited successfully, provides the complete contents of stdout/stderr if that assertion fails
This has unearthed a non-deterministic NPE that's occurring in the `PatchConnectorCommandTest` because the `DescribeConnectorCommand` instance that's created and used by `PatchConnectorCommand` has a null `spec` field. Strangely, this is not occurring consistently on my machine. I've been able to reproduce it as far back as 57afec337aecd3ab7cc2bbb65782b682fa51f3bb, so at the very least it's not …
=> MINOR: Sprinkle some syntactic sugar on our integration tests

src/main/java/org/kcctl/command/DescribeConnectorCommand.java, src/main/java/org/kcctl/command/PatchConnectorCommand.java, src/test/java/org/kcctl/IntegrationTest.java, src/test/java/org/kcctl/command/ApplyCommandTest.java, src/test/java/org/kcctl/command/ConnectorNamesCompletionCandidateCommandTest.java, src/test/java/org/kcctl/command/DeleteConnectorCommandTest.java, src/test/java/org/kcctl/command/DescribeConnectorCommandTest.java, src/test/java/org/kcctl/command/DescribePluginCommandTest.java, src/test/java/org/kcctl/command/GetConnectorsCommandTest.java, src/test/java/org/kcctl/command/GetLoggerCommandTest.java, src/test/java/org/kcctl/command/GetLoggersCommandTest.java, src/test/java/org/kcctl/command/GetOffsetsCommandTest.java, src/test/java/org/kcctl/command/GetPluginsCommandTest.java, src/test/java/org/kcctl/command/InfoCommandTest.java, src/test/java/org/kcctl/command/LoggerNamesCompletionCandidateCommandTest.java, src/test/java/org/kcctl/command/PatchCommandTest.java, src/test/java/org/kcctl/command/PauseConnectorCommandTest.java, src/test/java/org/kcctl/command/RestartConnectorCommandTest.java, src/test/java/org/kcctl/command/ResumeConnectorCommandTest.java, src/test/java/org/kcctl/command/StopConnectorCommandTest.java, src/test/java/org/kcctl/support/KcctlCommandContext.java
Fixes #353, depends on #354
The `DescribeConnectorCommand` is manually invoked by the `PatchConnectorCommand`, but without being given to a wrapping `CommandLine` instance. As a result, its `@CommandLine.Spec`-annotated `spec` field is not initialized in that case, and under some rare circumstances, the command will try to emit output via `spec.commandLine().getOut()::print` (or `println`, or `printf`, etc.). This causes a `NullPointerException`.
The scenario that leads to the attempted output is when the Connect cluster serves a 409 response due to a pending rebalance. This is otherwise gracefully handled with bounded retry logic by the `PatchConnectorCommand`.
This fix is a bit quick-and-dirty in that it doesn't prevent the `NullPointerException` from occurring in the extremely-rare …
=> #353 Fix flaky integration tests

pom.xml, src/main/java/org/kcctl/command/DescribeConnectorCommand.java, src/main/java/org/kcctl/command/PatchConnectorCommand.java, src/main/java/org/kcctl/service/KafkaConnectApi.java, src/main/java/org/kcctl/service/KafkaConnectConflictException.java, src/main/java/org/kcctl/service/KafkaConnectException.java, src/main/java/org/kcctl/service/KafkaConnectNotFoundException.java
Fixes #357
This uses a different approach than what was proposed in the issue, but the effect should be mostly the same. I drafted up the `retrying(() -> kafkaConnectApi.getConnectorConfig(conectorToPatch))` patch but realized that this would still have to be manually applied to all REST calls that could result in a 409 response, which seemed fairly brittle.
I did some research and it looks like we can get retry logic with our auto-generated REST client for free by bringing in a small extra dependency: https://quarkus.io/guides/smallrye-fault-tolerance
Since the API for describing retriable requests with this library is based on exception class, I added custom subclasses to the `KafkaConnectException` to help us distinguish between retriable and non-retriable operations. We could …
=> #357 Retry all REST requests on 409 errors

docker/Dockerfile, pom.xml, src/test/java/org/kcctl/ConnectTrunkDebeziumContainer.java, src/test/java/org/kcctl/IntegrationTest.java, src/test/resources/docker/Dockerfile
I have created a Dockerfile based on the debezium-connect image. 
This will simply add all the necessary stuff to build Kafka from the trunk branch. 
Just did some tests and seems that it is working. 
```bash
[mvitale@mvitale connect-config]$ kcctl apply -f postgres-connector-reg.json 
Created connector inventory-connector
[mvitale@mvitale connect-config]$ curl -X GET -H "Accept:application/json" localhost:8083/connectors/inventory-connector/offsets
{"offsets":[{"partition":{"server":"dbserver1"},"offset":{"last_snapshot_record":true,"lsn":34487416,"txId":768,"ts_usec":1691678351957450,"snapshot":true}}]}
[mvitale@mvitale connect-config]$ curl -X DELETE -H "Accept:application/json" localhost:8083/connectors/inventory-connector/offsets
{"error_code":400,"message":"Connectors must be in the …
```
=> Add Dockerfile to build a kafka connect image based on kafka trunk

.github/workflows/maven.yml, src/main/java/org/kcctl/command/GetLoggerCommand.java, src/main/java/org/kcctl/command/GetLoggersCommand.java, src/test/java/org/kcctl/IntegrationTest.java, src/test/java/org/kcctl/command/GetPluginsCommandTest.java
Adds a final Debezium tag to use for Kafka Connect 3.5, and a new tag to use for Kafka Connect 3.6.
Also brings in a few other unrelated commits to make CI happy.
=> MINOR: Update Debezium/Kafka Connect versions used in integration tests

README.md, kcctl_completion, src/main/java/org/kcctl/command/DeleteOffsetsCommand.java, src/main/java/org/kcctl/command/PatchCommand.java, src/main/java/org/kcctl/command/PatchOffsetsCommand.java, src/main/java/org/kcctl/service/KafkaConnectApi.java, src/test/java/org/kcctl/command/PatchOffsetsCommandTest.java
Fixes #374 
Usage:
```
Usage: kcctl patch offsets [-h] [[--kafka-topic=<topic>
--kafka-partition=<partition>
--kafka-offset=<offset>] |
[--source-partition=<partition>
--source-offset=<offset>]] NAME
Patches committed connector offsets
NAME     Name of the connector (e.g. 'my-connector')
-h, --help   Show this help message and exit.
--kafka-offset=<offset>
Desired offset of the Kafka topic (for sink connectors)
--kafka-partition=<partition>
Partition of the Kafka topic (for sink connectors)
--kafka-topic=<topic>
Name of the Kafka topic (for sink connectors)
--source-offset=<offset>
Desired offset (for source connectors), as a JSON object
--source-partition=<partition>
Partition (for source connectors), as a JSON object
```
Uses the `PATCH /connectors/{name}/offsets}` endpoint introduced …
=> #374 Add 'patch offsets' command

kcctl_completion, src/main/java/org/kcctl/command/GetLoggerCommand.java, src/main/java/org/kcctl/command/GetLoggersCommand.java, src/main/java/org/kcctl/command/LoggerNamesCompletionCandidateCommand.java, src/main/java/org/kcctl/command/PatchLogLevelCommand.java, src/main/java/org/kcctl/service/KafkaConnectApi.java, src/main/java/org/kcctl/service/LoggerLevel.java, src/test/java/org/kcctl/IntegrationTest.java, src/test/java/org/kcctl/command/PatchLogLevelCommandTest.java
Fixes #395
New usage:
```
Usage: kcctl patch logger [-h] -l=<level> [-s=<scope>] Logger NAME
Changes the log level of given class/Connector path
Logger NAME       Name of the logger
-h, --help            Show this help message and exit.
-l, --level=<level>   Name of log level to apply
-s, --scope=<scope>   The scope of the logging adjustment; e.g., 'worker' or
'cluster'
```
If a scope is provided, then it is included in the REST request via the `?scope` URL query parameter; if no scope is provided, the URL query parameter is omitted from the request.
There is no restriction on permitted values for scopes, but only the values "worker" and "cluster" are suggested during autocompletion.
Other changes not directly related to the new command:
- 7a92d18: Pick up some autoformatting changes that …
=> #395 Add '--scope' argument to 'patch logger'

.github/workflows/early-access.yml, .github/workflows/maven.yml, .github/workflows/release.yml, pom.xml
- Remove duplicate release configuration
- Perform a build on Linux before packaging per platform
- Skip running tests during packaging
- Upgrade upload/download GH actions
=> Simplify release

src/main/java/org/kcctl/command/PatchOffsetsCommand.java, src/test/java/org/kcctl/command/PatchOffsetsCommandTest.java
Fixes #422, and adds some extra testing to ensure that the source and sink offset argument types are (and remain) mutually exclusive.
=> #422 Fix NPE for 'kcctl patch offsets' without payload
