- .github/workflows/early-access.yml
- .github/workflows/release.yml
Follow up to https://twitter.com/gunnarmorling/status/1423022723350122497?s=20
I've got a small reduction of the binary on my local environment, from 44M to 41M.
> 🍷 Update Graal to 21.2.0

- src/main/java/dev/morling/kccli/command/DescribeConnectorCommand.java
- src/main/java/dev/morling/kccli/service/KafkaConnectApi.java
- src/main/java/dev/morling/kccli/util/Tuple.java
- src/main/java/dev/morling/kccli/util/Version.java
- src/test/java/dev/morling/kccli/util/VersionTest.java
This maps to /connectors/<connector>/tasks-config and returns the configuration of all tasks of a connector.
Usage: kcctl describe tasks-config <connector>
> Add describe tasks-config command

- src/main/java/dev/morling/kccli/command/ConfigCommand.java
- src/main/java/dev/morling/kccli/command/GetContextCommand.java
added config get-context command and description in set-context﻿
> added config get-context command and description in set-context #3

- kcctl_completion
help, version, get context added in completion
> help, version, get context added in completion #37

- kcctl_completion
- src/main/java/dev/morling/kccli/command/PatchCommand.java
- src/main/java/dev/morling/kccli/command/PatchConnectorCommand.java
> 🩹 Add a command to patch connector parameters

- .github/dependabot.yml
> 🤖 Add Dependabot

- src/main/java/dev/morling/kccli/util/ConfigurationContext.java
set-context is a sub-command of kcctl config.
> Fixed references to "kcctl set-context"

- src/main/java/dev/morling/kccli/command/DescribeConnectorCommand.java
added simple version check, from debezium 1.2 it support topics end point﻿
> #65 added version check for topics api

- src/main/java/dev/morling/kccli/command/ApplyCommand.java
- src/main/java/dev/morling/kccli/command/DescribeConnectorCommand.java
- #61 handled exception and showed message rather stacktrace
> handled exception for invalid connector config

- src/main/java/org/kcctl/command/DeleteConnectorCommand.java
> fix: Handle attempt to delete non-existing connector gracefully

- README.md
- pom.xml
- src/test/java/org/kcctl/service/KafkaConnectClientHeadersFactoryTest.java
> ⬆️  #113 Updating to Java 17

- src/main/java/org/kcctl/command/KcCtlCommand.java
- src/main/java/org/kcctl/service/ExecutionExceptionHandler.java
- src/test/java/org/kcctl/service/ExecutionExceptionHandlerTest.java
> 🥅 #124 Gracefully handling non-available KC REST API

- README.md
- pom.xml
Fixes https://github.com/kcctl/kcctl/issues/127
> 🍺 Add Homebrew packager

- .github/workflows/early-access.yml
- README.md
- src/test/java/org/kcctl/command/ApplyCommandTest.java
- src/test/java/org/kcctl/command/ConnectorNamesCompletionCandidateCommandTest.java
- src/test/java/org/kcctl/command/DeleteConnectorCommandTest.java
- src/test/java/org/kcctl/command/GetConnectorsCommandTest.java
- src/test/java/org/kcctl/command/GetLoggerCommandTest.java
- src/test/java/org/kcctl/command/GetLoggersCommandTest.java
- src/test/java/org/kcctl/command/GetPluginsCommandTest.java
- src/test/java/org/kcctl/command/InfoCommandTest.java
- src/test/java/org/kcctl/command/LoggerNamesCompletionCandidateCommandTest.java
- src/test/java/org/kcctl/command/PauseConnectorCommandTest.java
Docker isn't available in that environment.
> 🧪 #44 Skipping integration tests on GH Actions for macOS;

- .github/workflows/early-access.yml
- .github/workflows/release.yml
> #147 used the github action graalvm/setup-graalvm

- src/main/java/org/kcctl/command/DescribeConnectorCommand.java
https://github.com/kcctl/kcctl/issues/182
> #182 Want to sort the connector config info when executing the describe command

- .github/workflows/early-access.yml
- .github/workflows/release.yml
- README.md
- src/main/java/org/kcctl/command/ApplyCommand.java
- src/main/java/org/kcctl/command/DescribeConnectorCommand.java
- src/main/java/org/kcctl/command/GetConnectorsCommand.java
- src/main/java/org/kcctl/command/GetPluginsCommand.java
- src/main/java/org/kcctl/command/InfoCommand.java
- src/main/java/org/kcctl/command/TaskNamesCompletionCandidateCommand.java
- src/main/java/org/kcctl/service/ConfigInfos.java
- src/main/java/org/kcctl/service/ConnectorExpandInfo.java
- src/main/java/org/kcctl/service/ConnectorInfo.java
- src/main/java/org/kcctl/service/ConnectorPlugin.java
- src/main/java/org/kcctl/service/ConnectorState.java
- src/main/java/org/kcctl/service/ConnectorStatusInfo.java
- src/main/java/org/kcctl/service/KafkaConnectApi.java
- src/main/java/org/kcctl/service/KafkaConnectInfo.java
- src/main/java/org/kcctl/service/TaskInfo.java
- src/main/java/org/kcctl/service/TopicsInfo.java
- src/main/java/org/kcctl/util/Tuple.java
- src/test/java/org/kcctl/command/GetConnectorsCommandTest.java
https://github.com/kcctl/kcctl/issues/184
> #184 Introduce a new "expand" api to request all connectors status and config info

- .github/workflows/maven.yml
Closes: https://github.com/kcctl/kcctl/issues/381
> #381 Add `TRUNK` to CI connect version

- README.md
- src/main/java/org/kcctl/command/DeleteCommand.java
> #424 Add DeleteOffsetsCommand as subcommand of DeleteCommand

- src/main/java/org/kcctl/command/ConfigCommand.java
- src/main/java/org/kcctl/command/RemoveContextCommand.java
- src/main/java/org/kcctl/service/Configuration.java
- src/main/java/org/kcctl/util/ConfigurationContext.java
- src/test/java/org/kcctl/util/ConfigurationContextTest.java
Add the command to allow for deletion of contexts that are not necessary anymore.
For precaution I chose to not allow the user to delete the current context, forcing them to change the context before deleting it.
> #399 Remove context

- pom.xml
- src/main/java/org/kcctl/command/PatchOffsetsCommand.java
- src/test/java/org/kcctl/ConnectTrunkDebeziumContainer.java
- src/test/java/org/kcctl/IntegrationTest.java
- src/test/java/org/kcctl/NativeImageEnabledDebeziumContainer.java
- src/test/java/org/kcctl/command/GetPluginsCommandTest.java
- src/test/resources/docker/Dockerfile
Also using native Kafka image for testing.
> #469 Support for Debezium 3.x container images;
